name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
# # command to run tests, e.g. python setup.py test
    - name: Run tests
      run: |
        poetry run pytest
